### ISSUE TITLE
Course advertising

### ISSUE THREAD

**Issue by docsteveharris** [datascibc/Data-Science-for-Docs#17]
- [ ] ideas from @tompollard 
- [ ] ideas from @ngageorange 
- [x] ideas from @dannyjnwong 
- [ ] ideas from @mn936148 
- [ ] ideas from @finncatling 
- [ ] ideas from Rui
- [ ] ideas from @docsteveharris

Please add your notes at https://github.com/datascibc/course/wiki/advertising

**Comment by ngageorange** [comment]
I've got access to the imperial school of anaesthesia website; I can make an event there and it'll be official with the school....

**Comment by dannyjnwong** [comment]
I can advertise amongst the South London Anaesthesia School as well as through the NIAA, [PLAN (Pan-London Audit Network](http://www.uk-plan.net) and [RAFT (Research and Audit Federation of Trainees)](http://www.raftrainees.com).

I can also fire our [MailChimp newsletter](http://us9.campaign-archive1.com/?u=a1602a3d444e0fdc20ae6a64a&id=9c9d9cbfc2&e=[UNIQID]) again.

**Comment by dannyjnwong** [comment]
BTW, I am happy to be made in charge of advertising and publicity.

**Comment by docsteveharris** [comment]
Could potentially tap into the MSc and MPH programmes at LSHTM etc
