### ISSUE TITLE
Assign volunteers to lecture prep and then rota these

### ISSUE THREAD

**Issue by docsteveharris** [datascibc/Data-Science-for-Docs#19]
People to self assign

- [ ] introduction to data science, why it's important, explosion in data in ITU (and in theatres), good visualisations that we've made in the past. Get people hyped up about this course. Maybe half an hour or so max? steve harris 
- [ ] excel sheets done right Ed Palmer
- [x] tidying data in R @ngageorange 
- [ ] exploratory data analysis via visualisation
- [ ] inspecting and simple data visualisation @finncatling 
- [ ] statistics (perhaps done by following the format of 'Statistics done wrong' by Alex Reinhart) @sundhiya
- [ ] R markdown and programmers notebooks / reproducible research @dannyjnwong 
- [ ] Introduction to MIMIC @tompollard

**Comment by docsteveharris** [comment]
Need to send email to people to recruit

**Comment by ngageorange** [comment]
I think it would be nice for me to learn R properly so perhaps, if no one has any objections, for me to work on the first draft of the "Tidying data in R" bit?

I'm thinking it'll be essentially what Steve wrote as the intro into R followed by specifics on data tidying...

**Comment by dannyjnwong** [comment]
I'm happy to do either -Inspecting and visualisation, or -Rmarkdown and reproducibility!

And also do you think we should stick to base R or should we introduce people to the capabilities of other packages, eg. dplyr and ggplot2?

**Comment by finncatling** [comment]
Happy to do (in the interest of improving my own knowledge) either statistics, or inspecting and visualisation (as I'm used to python, not R).

**Comment by finncatling** [comment]
...although we would need to be more specific on which parts of statistics we think are relevant to the course

**Comment by docsteveharris** [comment]
Steve to close issue but splitting into constituent parts
