### ISSUE TITLE
Set-up course website

### ISSUE THREAD

**Issue by docsteveharris** [datascibc/Data-Science-for-Docs#4]
- [x] choose jekyll theme
- [ ] add jekyll structure to repo
- [ ] publish template site

**Comment by docsteveharris** [comment]
Finn - have think. No pressure but you will have more skills than the rest of us put together

**Comment by finncatling** [comment]
Certainly happy to help with the coding, but probably best if we all contribute to the content?

I've had a go at a first draft specification for the website [here](https://github.com/datascibc/course/wiki/Website-Specification). Other contributions would be very welcome :)

**Comment by docsteveharris** [comment]
Hi Finn. Completely agree. I like the idea of a mini-rota for contributing content. All your thoughts seem sensible, and I think the theme looks good. Let's add this to the agenda for the next meeting, get feedback from the others and then we can go.

**Comment by dannyjnwong** [comment]
I like the idea of using rmarkdown, Jekyll and rstudio with GitHub hosting: http://www.r-bloggers.com/blogging-with-rmarkdown-knitr-and-jekyll/

**Comment by dannyjnwong** [comment]
Here's another example https://github.com/yihui/knitr-jekyll

**Comment by dannyjnwong** [comment]
I've managed to get myself up and running with a Jekyll blog hosted on GitHub. You can check it out [here](dannyjnwong.github.io).

The way I've made it work is that I will make posts in Rmarkdown in Rstudio, this then gets knitted into a markdown file using a helper function and figures which get produced will be placed in a figures/ directory and linked properly.

I think we can deploy similarly for datascibc especially if we are working with R.

**Comment by docsteveharris** [comment]
Great Danny. Really nice, and I like the idea. 
I note that you have postcodes, dates, times etc in the example - just be careful about putting that on the web - unless they're simulated of course.

S 


On 24 January 2016 at 22:03:07, Danny Wong (notifications@github.com) wrote:

I've managed to get myself up and running with a Jekyll blog hosted on GitHub. You can check it out here.

The way I've made it work is that I will make posts in Rmarkdown in Rstudio, this then gets knitted into a markdown file using a helper function and figures which get produced will be placed in a figures/ directory and linked properly.

I think we can deploy similarly for datascibc especially if we are working with R.

**Comment by dannyjnwong** [comment]
Good point. Had forgotten about that. Will take that chunk down.

Kindest regards,
Danny Wong

**Comment by docsteveharris** [comment]
thanks @finncatling - going to make page 1

**Comment by docsteveharris** [comment]
Can mailing list from old website can be added to new website?

**Comment by docsteveharris** [comment]
@finncatling Do you think it is possible that we might get the website up? Would be keen to advertise the course, and it would be nice if we had the website as a point of reference? If it's not going to fit with your work schedule, just say, and I'll hack something minimimal

**Comment by finncatling** [comment]
I don't think I'll have time to progress it much this week unfortunately -
I have my head down trying to write up stuff for my lab project. I can try
and put together a first draft during the week after?

**Comment by docsteveharris** [comment]
ok. sounds fine. let's re-group in a week or so and see

**Comment by finncatling** [comment]
Great OK.

**Comment by docsteveharris** [comment]
Adding a note to consider course branding in line with website etc
Anyone fancy thinking of a logo?
Use the website colour scheme on the slides (via CSS)

**Comment by finncatling** [comment]
You can get a nice logo designed by someone on people per hour for about
£50 - worth doing?

**Comment by docsteveharris** [comment]
Great idea. What about this one

http://www.peopleperhour.com/hourlie/design-a-professional-logo-100-5-star-reviews-on-all-sold/116898?ref=search

Can we brainstorm a few ideas?

Will add to slack for feedback
