### ISSUE TITLE
Find video explaining directory navigation

### ISSUE THREAD

**Issue by DocEd** [datascibc/Data-Science-for-Docs#74]
Major roadblock in previous courses was understanding directory structure/navigation.

Find a youtube video that explains it well and make it part of the prerequisites to go through before attending course.
Update teaching to have split screen left/right with finder/explorer 1 side and terminal/command line other to consolidate learning on the day

**Comment by docsteveharris** [comment]
Probably the best one I can find for unix - https://www.youtube.com/watch?v=j6vKLJxAKfw
