### ISSUE TITLE
Merge data pipeline and intro lectures

### ISSUE THREAD

**Issue by DocEd** [datascibc/Data-Science-for-Docs#77]
- Update data pipeline lecture to be about the breast data. ALL data in the course should now be consistently about the same thing
- Move google sheets to "extra / homework" section, but not part of sessions any more

**Comment by docsteveharris** [comment]
@ahmedalhindawi1 just checking on progress for this one?

**Comment by docsteveharris** [comment]
Ahmed to have editorial oversight of course materials to check all are using the same (breast) data

**Comment by docsteveharris** [comment]
We need to make sure all occurrences of where the breast data has been brought into the lecture we assign it to the object `RCT`. I've done this for both the lectures I gave (getting data into R and wrangling)
